name: Britive-GitHub Federated Access for GCP via OpenID Connect

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'  # Runs daily at 08:00 UTC

permissions:
  id-token: write
  contents: read

jobs:
  federated-gcp-access:
    runs-on: ubuntu-latest

    env:
      GCS_BUCKET_NAME: acme-corp-backup-storage
      GCP_PROJECT_ID: 810261868576

    steps:
      - name: Install pybritive and gcloud CLI
        run: |
          pip install pybritive --quiet

      - name: Checkout GCP access from Britive and authenticate
        run: |
          echo "Checking out GCP login command from Britive..."
          set +x
          eval "$(pybritive checkout -t demo.britive-app.com -m gcloudauth 'GCP - CIS/GCP - CIS/ACME-Storage-Bucket' -P github-britive | grep '^gcloud auth activate-service-account')"
          set -x

      - name: Confirm GCP Access (safe output)
        run: |
          echo "Verifying GCP access..."
          gcloud config list account --format="value(core.account)"
          echo "Setting project ID..."
          gcloud config set project $GCP_PROJECT_ID

      - name: Retry GCS Bucket Listing (up to 5 attempts)
        run: |
          echo "Retrying bucket listing..."
          for i in {1..5}; do
            echo "Attempt $i: Listing bucket contents..."
            if gsutil ls gs://$GCS_BUCKET_NAME/; then
              echo "Bucket listing succeeded."
              break
            else
              echo "Bucket listing failed. Retrying in 15 seconds..."
              sleep 15
            fi
          done

      - name: Create Daily Backup File in GCS
        run: |
          BACKUP_DATE=$(date +%Y-%m-%d)
          BACKUP_FILENAME="Backup-${BACKUP_DATE}.bak"
          echo "Creating backup file: $BACKUP_FILENAME"
          echo "Daily Backup $BACKUP_DATE" > /tmp/$BACKUP_FILENAME
          gsutil cp -n /tmp/$BACKUP_FILENAME gs://$GCS_BUCKET_NAME/$BACKUP_FILENAME
          echo "Successfully created backup file: gs://$GCS_BUCKET_NAME/$BACKUP_FILENAME"
          echo "Current files in backup bucket:"
          gsutil ls gs://$GCS_BUCKET_NAME/
